// Command gen-go turns the embedded SharePoint catalogs (go-spo/spec) into typed Go
// bindings in package spo. For each admin object (the tenant singleton, site
// collections) it emits a Set<obj>Params struct (one tri-state field per knob), a
// setProps<obj> helper that compiles bound fields into CSOM <SetProperty> actions,
// a Normalize<obj> that turns read-back enum integers into member names, and (for
// the tenant singleton) the Get/Set service methods. Non-singleton service methods
// (site CRUD, async) are hand-written in spo.go against these generated pieces.
//
//	go run ./cmd/gen-go
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/terraprovider/go-spo/spec"
)

// object binds a catalog to its generated surface. kind selects how the object is
// addressed: "singleton" constructs the object (Tenant); "url" resolves it by URL
// via Tenant.GetSitePropertiesByUrl (SiteProperties).
type object struct {
	goName string // "SPOTenant", "SPOSite"
	cat    *spec.ObjectCatalog
	kind   string // "singleton" | "url"
}

func main() {
	out := flag.String("out", "spo/zz_generated_spo.go", "output file")
	flag.Parse()

	tenant, err := spec.Tenant()
	if err != nil {
		log.Fatal(err)
	}
	site, err := spec.Site()
	if err != nil {
		log.Fatal(err)
	}
	objs := []object{
		{"SPOTenant", tenant, "singleton"},
		{"SPOSite", site, "url"},
	}
	src, err := generate(objs)
	if err != nil {
		log.Fatal(err)
	}
	formatted, err := format.Source(src)
	if err != nil {
		_ = os.WriteFile(*out+".raw", src, 0o644)
		log.Fatalf("gofmt: %v (unformatted written to %s.raw)", err, *out)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("gen-go: wrote %s\n", *out)
}

var nonIdent = regexp.MustCompile(`[^A-Za-z0-9]+`)

func enumVar(fullType string) string { return "enum" + nonIdent.ReplaceAllString(fullType, "_") }

type knobField struct {
	prop     spec.Property
	goType   string
	wireType string
	elemType string
	enumVar  string
}

func classify(p spec.Property) (knobField, bool) {
	kf := knobField{prop: p}
	if p.IsCollection || p.CsomType == "Array" {
		switch p.ElementType {
		case "Guid":
			kf.goType, kf.wireType, kf.elemType = "[]string", "spoapi.TypeArray", "spoapi.TypeGuid"
		case "String":
			kf.goType, kf.wireType, kf.elemType = "[]string", "spoapi.TypeArray", "spoapi.TypeString"
		default:
			return kf, false
		}
		return kf, true
	}
	switch p.CsomType {
	case "Boolean":
		kf.goType, kf.wireType = "*bool", "spoapi.TypeBoolean"
	case "String":
		kf.goType, kf.wireType = "*string", "spoapi.TypeString"
	case "Guid":
		kf.goType, kf.wireType = "*string", "spoapi.TypeGuid"
	case "Int16":
		kf.goType, kf.wireType = "*int64", "spoapi.TypeInt16"
	case "Int32":
		kf.goType, kf.wireType = "*int64", "spoapi.TypeInt32"
	case "Int64":
		kf.goType, kf.wireType = "*int64", "spoapi.TypeInt64"
	case "Double":
		kf.goType, kf.wireType = "*float64", "spoapi.TypeDouble"
	case "Enum":
		if p.EnumType == "" {
			return kf, false
		}
		kf.goType, kf.wireType, kf.enumVar = "*string", "spoapi.TypeEnum", enumVar(p.EnumType)
	default:
		return kf, false
	}
	return kf, true
}

func generate(objs []object) ([]byte, error) {
	// classify each object's knobs; collect the enums actually referenced.
	fieldsByObj := map[string][]knobField{}
	usedEnums := map[string]bool{}
	for _, o := range objs {
		var fields []knobField
		skipped := 0
		for _, p := range o.cat.Knobs() {
			kf, ok := classify(p)
			if !ok {
				skipped++
				continue
			}
			if kf.enumVar != "" {
				if _, has := o.cat.Enums[p.EnumType]; !has {
					skipped++
					continue
				}
				usedEnums[p.EnumType] = true
			}
			fields = append(fields, kf)
		}
		sort.Slice(fields, func(i, j int) bool { return fields[i].prop.Name < fields[j].prop.Name })
		fieldsByObj[o.goName] = fields
		fmt.Printf("gen-go: %s — %d knob fields (%d skipped)\n", o.goName, len(fields), skipped)
	}
	// enum type -> its owning catalog's value map (any catalog that has it).
	enumVals := map[string]map[string]int{}
	for _, o := range objs {
		for t, v := range o.cat.Enums {
			if usedEnums[t] {
				enumVals[t] = v
			}
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by cmd/gen-go from the spo-powershell-api-re catalog. DO NOT EDIT.\n\n")
	b.WriteString("package spo\n\n")
	b.WriteString(`import (
	"context"
	"strconv"

	"github.com/terraprovider/go-spo/spoapi"
)` + "\n\n")

	// Shared enum value maps (name → int), emitted once.
	enumTypes := sortedKeys(usedEnums)
	for _, t := range enumTypes {
		fmt.Fprintf(&b, "// %s\nvar %s = map[string]int{\n", t, enumVar(t))
		for _, n := range sortedKeys2(enumVals[t]) {
			fmt.Fprintf(&b, "\t%q: %d,\n", n, enumVals[t][n])
		}
		b.WriteString("}\n\n")
	}
	if len(enumTypes) > 0 {
		b.WriteString(`// enumVal resolves an enum member name (or numeric string) to its integer wire
// value. Unknown names fall back to 0 (the provider constrains input).
func enumVal(m map[string]int, s string) any {
	if v, ok := m[s]; ok {
		return v
	}
	if n, err := strconv.Atoi(s); err == nil {
		return n
	}
	return 0
}` + "\n\n")
	}

	for _, o := range objs {
		emitObject(&b, o, fieldsByObj[o.goName], enumVals)
	}
	return []byte(b.String()), nil
}

func emitObject(b *strings.Builder, o object, fields []knobField, enumVals map[string]map[string]int) {
	name := o.goName
	keyed := o.kind == "url"

	// Params struct (URL-keyed objects carry the site Identity as the first field).
	fmt.Fprintf(b, "// Set%sParams holds the admin knobs settable via %s.\n", name, o.cat.SetCmdlet)
	fmt.Fprintf(b, "// Each field is tri-state: nil/unset = leave unchanged. Generated from %s (%d knobs).\n", o.cat.Object, len(fields))
	fmt.Fprintf(b, "type Set%sParams struct {\n", name)
	if keyed {
		fmt.Fprintf(b, "\tIdentity string `spo:%q` // the site URL (Set-SPOSite -Identity)\n", "Identity")
	}
	for _, f := range fields {
		fmt.Fprintf(b, "\t%s %s `spo:%q` // %s\n", f.prop.Name, f.goType, f.prop.Name, fieldDoc(f))
	}
	b.WriteString("}\n\n")

	// setProps helper.
	fmt.Fprintf(b, "// setProps%s compiles the bound (non-nil) knobs into CSOM SetProperty actions.\n", name)
	fmt.Fprintf(b, "func setProps%s(p Set%sParams) []spoapi.SetProp {\n\tvar set []spoapi.SetProp\n", name, name)
	for _, f := range fields {
		fn := f.prop.Name
		fmt.Fprintf(b, "\tif p.%s != nil {\n", fn)
		switch {
		case f.enumVar != "":
			fmt.Fprintf(b, "\t\tset = append(set, spoapi.SetProp{Name: %q, Type: %s, Value: enumVal(%s, *p.%s)})\n", fn, f.wireType, f.enumVar, fn)
		case f.elemType != "":
			fmt.Fprintf(b, "\t\tset = append(set, spoapi.SetProp{Name: %q, Type: %s, ElemType: %s, Value: p.%s})\n", fn, f.wireType, f.elemType, fn)
		default:
			fmt.Fprintf(b, "\t\tset = append(set, spoapi.SetProp{Name: %q, Type: %s, Value: *p.%s})\n", fn, f.wireType, fn)
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn set\n}\n\n")

	// Reverse enum maps + Normalize.
	fmt.Fprintf(b, "// %sEnumNames maps each enum property to its integer→name lookup (read-back).\n", lower(name))
	fmt.Fprintf(b, "var %sEnumNames = map[string]map[int]string{\n", lower(name))
	for _, f := range fields {
		if f.enumVar == "" {
			continue
		}
		fmt.Fprintf(b, "\t%q: {", f.prop.Name)
		vals := enumVals[f.prop.EnumType]
		parts := make([]string, 0, len(vals))
		for _, n := range sortedKeys2(vals) {
			parts = append(parts, fmt.Sprintf("%d: %q", vals[n], n))
		}
		b.WriteString(strings.Join(parts, ", "))
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(b, `// Normalize%s rewrites a read-back %s object in place: enum properties (returned
// as integers) become their member name.
func Normalize%s(obj map[string]any) {
	for prop, names := range %sEnumNames {
		if v, ok := obj[prop]; ok {
			if f, ok := v.(float64); ok {
				if nm, ok := names[int(f)]; ok {
					obj[prop] = nm
				}
			}
		}
	}
}

`, name, name, name, lower(name))

	if keyed {
		emitURLKeyedMethods(b, o, name)
	} else {
		emitSingletonMethods(b, o, name)
	}
}

// emitSingletonMethods emits Get/Set for a constructor-addressed object (Tenant).
func emitSingletonMethods(b *strings.Builder, o object, name string) {
	fmt.Fprintf(b, `// Get%sParams is the (empty) read params for the singleton (no key).
type Get%sParams struct{}

// Get%s reads the object (construct → query-all), normalises enum read-backs, and
// injects a stable Identity (the admin URL) so the singleton has a non-empty id.
func (s *Service) Get%s(ctx context.Context, _ Get%sParams) (*spoapi.Result, error) {
	res, err := s.C.Invoke(ctx, spoapi.Op{CmdletName: %q, TypeID: spoapi.TenantTypeID, Query: true})
	if err != nil {
		return nil, err
	}
	for _, obj := range res.Value {
		Normalize%s(obj)
		if _, ok := obj["Identity"]; !ok {
			obj["Identity"] = s.C.AdminURL()
		}
	}
	return res, nil
}

// Set%s applies the bound knobs (construct → SetProperty per knob → Update → read back).
func (s *Service) Set%s(ctx context.Context, p Set%sParams) (*spoapi.Result, error) {
	res, err := s.C.Invoke(ctx, spoapi.Op{
		CmdletName: %q, TypeID: spoapi.TenantTypeID,
		Set: setProps%s(p), Update: true, Query: true,
	})
	if err != nil {
		return nil, err
	}
	for _, obj := range res.Value {
		Normalize%s(obj)
		if _, ok := obj["Identity"]; !ok {
			obj["Identity"] = s.C.AdminURL()
		}
	}
	return res, nil
}

`, name, name, name, name, name, o.cat.GetCmdlet, name,
		name, name, name, o.cat.SetCmdlet, name, name)
}

// emitURLKeyedMethods emits Get/Set for a site addressed by URL via
// Tenant.GetSitePropertiesByUrl(url, true). Set is Set+Update+read-back in one
// round-trip; note some site changes complete asynchronously server-side.
func emitURLKeyedMethods(b *strings.Builder, o object, name string) {
	fmt.Fprintf(b, `// Get%sParams targets a site collection by URL.
type Get%sParams struct {
	Identity string `+"`spo:\"Identity\"`"+` // the site URL
}

func siteChain(url string) []spoapi.PathStep {
	return []spoapi.PathStep{{
		Method: "GetSitePropertiesByUrl",
		Params: []spoapi.Param{{Type: spoapi.TypeString, Value: url}, {Type: spoapi.TypeBoolean, Value: true}},
	}}
}

// Get%s reads a site collection's admin settings (%s -Identity <url>).
func (s *Service) Get%s(ctx context.Context, p Get%sParams) (*spoapi.Result, error) {
	res, err := s.C.Invoke(ctx, spoapi.Op{CmdletName: %q, TypeID: spoapi.TenantTypeID, Chain: siteChain(p.Identity), Query: true})
	if err != nil {
		return nil, err
	}
	for _, obj := range res.Value {
		Normalize%s(obj)
		if _, ok := obj["Identity"]; !ok {
			obj["Identity"] = p.Identity
		}
	}
	return res, nil
}

// Set%s applies the bound knobs to an existing site (%s -Identity <url>).
func (s *Service) Set%s(ctx context.Context, p Set%sParams) (*spoapi.Result, error) {
	res, err := s.C.Invoke(ctx, spoapi.Op{
		CmdletName: %q, TypeID: spoapi.TenantTypeID,
		Chain: siteChain(p.Identity), Set: setProps%s(p), Update: true, Query: true,
	})
	if err != nil {
		return nil, err
	}
	for _, obj := range res.Value {
		Normalize%s(obj)
		if _, ok := obj["Identity"]; !ok {
			obj["Identity"] = p.Identity
		}
	}
	return res, nil
}

`, name, name,
		name, o.cat.GetCmdlet, name, name, o.cat.GetCmdlet, name,
		name, o.cat.SetCmdlet, name, name, o.cat.SetCmdlet, name, name)
}

func fieldDoc(f knobField) string {
	if f.enumVar != "" {
		if len(f.prop.ValidateSet) > 0 {
			return "enum: " + strings.Join(f.prop.ValidateSet, " | ")
		}
		return "enum: " + f.prop.EnumType
	}
	if f.elemType != "" {
		return "array of " + strings.TrimPrefix(f.elemType, "spoapi.Type")
	}
	return f.prop.CsomType
}

func lower(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedKeys2(m map[string]int) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
